<a href="https://colab.research.google.com/github/janzaw04/machinelearning/blob/main/WYK_3_Zadanie_Zawadzki_Jan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import gym
import numpy as np
import random

In [25]:
env = gym.make("Taxi-v3").env
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [26]:
env.reset() # reset environment to a new, random state
env.render()

print("Action Space {}".format(env.action_space))
print("State Space {}".format(env.observation_space))

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

Action Space Discrete(6)
State Space Discrete(500)


In [27]:
import numpy as np

state = env.encode(4, 1, 2, 3) # (taxi row, taxi column, passenger index, destination index)
print("State:", state)
env.s = state
env.render()

State: 431
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [30]:
# Tabela Q 500 przykładów(przestrzeń obserwacji = 5*5*5*4 = 500) - 6 akcji (wschód, zachód, północ, południe, zabierz, wysadź)
q_table = np.zeros([env.observation_space.n,env.action_space.n])
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [31]:
alpha = 0.1 # współczynnik uczenia się
gamma = 0.9 # faktyczna zniżka
epsilon = 0.1 # współczynnik eksploracji
reward_list = [] # jest zdefiniowana, aby zachować nagrody
dropout_list = [] # jest zdefiniowana, aby zachować błędne odrzuty, aby zobaczyć jak działa algorytm

In [32]:
episode_number = 5000

for i in range(1,episode_number):
    
    # init enviroment
    state = env.reset()
    
    reward_count = 0
    dropouts = 0
    
    while True:
        
        # exploit vs explore to find action epsilon 0.1 => %10 explore %90 explotit
        if random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])
            
        # action process and take reward / take observation
        next_state, reward, done, _ = env.step(action)
        
        # q learning funct
        
        old_value = q_table[state, action]  #old value
        next_max = np.max(q_table[next_state]) #next max
        
        next_value = (1-alpha)*old_value + alpha*(reward + gamma*next_max)
        # q table update
        q_table[state,action] = next_value
        
        # update state
        state = next_state
        
        # find wrong dropout 
        if reward == -10:
            dropouts += 1
            
        if done:
            break
        
        reward_count  += reward
    if i%10 == 0:
        
        dropout_list.append(dropouts)
        reward_list.append(reward_count)
        print("Episode: {}, reward {}, wrong dropout {}".format(i, reward_count,dropouts))

Episode: 10, reward -296, wrong dropout 5
Episode: 20, reward -787, wrong dropout 20
Episode: 30, reward -643, wrong dropout 19
Episode: 40, reward -391, wrong dropout 7
Episode: 50, reward -475, wrong dropout 11
Episode: 60, reward -365, wrong dropout 10
Episode: 70, reward -546, wrong dropout 16
Episode: 80, reward -99, wrong dropout 1
Episode: 90, reward -450, wrong dropout 12
Episode: 100, reward -370, wrong dropout 11
Episode: 110, reward -214, wrong dropout 5
Episode: 120, reward -122, wrong dropout 5
Episode: 130, reward -205, wrong dropout 6
Episode: 140, reward -285, wrong dropout 9
Episode: 150, reward -284, wrong dropout 10
Episode: 160, reward -51, wrong dropout 1
Episode: 170, reward -279, wrong dropout 9
Episode: 180, reward -68, wrong dropout 1
Episode: 190, reward -182, wrong dropout 7
Episode: 200, reward -133, wrong dropout 1
Episode: 210, reward -304, wrong dropout 8
Episode: 220, reward -266, wrong dropout 8
Episode: 230, reward -127, wrong dropout 4
Episode: 240, r

In [33]:
env.s = env.encode(0,0,3,4) # env.encode(taxi row, taxi col, passenger index, destination)
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
